#
# Makefile for documents and templates
# Author: Stanislav Kruchinin <stanislav.kruchinin@gmail.com>
#

TARGET ?= thesis
BIBTEX := biber
BIBTEXFLAGS := 

include ../../include/latex.mk

all: pdf

allpdf: pdf

alldvi: dvi

help: .help
	@echo "  all          alias for pdf target" ;\
	 echo "  allpdf       alias for pdf target" ;\
	 echo "  alldvi       alias for dvi target" ;\
